# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/kintex_5cam_cln_fifo_wrk/kintex_5cam/K7_verilog/K7_verilog.srcs/sources_1/ip/async_fifo/async_fifo.xci
# IP: The module: 'async_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/kintex_5cam_cln_fifo_wrk/kintex_5cam/K7_verilog/K7_verilog.gen/sources_1/ip/async_fifo/async_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/kintex_5cam_cln_fifo_wrk/kintex_5cam/K7_verilog/K7_verilog.gen/sources_1/ip/async_fifo/async_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/kintex_5cam_cln_fifo_wrk/kintex_5cam/K7_verilog/K7_verilog.srcs/sources_1/ip/async_fifo/async_fifo.xci
# IP: The module: 'async_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/kintex_5cam_cln_fifo_wrk/kintex_5cam/K7_verilog/K7_verilog.gen/sources_1/ip/async_fifo/async_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/kintex_5cam_cln_fifo_wrk/kintex_5cam/K7_verilog/K7_verilog.gen/sources_1/ip/async_fifo/async_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
