# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/kintex_map_5cam_Y8_4dec/kintex_5cam/kintex_camlink_tx_231023.srcs/sources_1/ip/async_fifo_28by256/async_fifo_28by256.xci
# IP: The module: 'async_fifo_28by256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/kintex_map_5cam_Y8_4dec/kintex_5cam/kintex_camlink_tx_231023.gen/sources_1/ip/async_fifo_28by256/async_fifo_28by256.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_28by256'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/kintex_map_5cam_Y8_4dec/kintex_5cam/kintex_camlink_tx_231023.gen/sources_1/ip/async_fifo_28by256/async_fifo_28by256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_28by256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/kintex_map_5cam_Y8_4dec/kintex_5cam/kintex_camlink_tx_231023.gen/sources_1/ip/async_fifo_28by256/async_fifo_28by256_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_28by256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/kintex_map_5cam_Y8_4dec/kintex_5cam/kintex_camlink_tx_231023.srcs/sources_1/ip/async_fifo_28by256/async_fifo_28by256.xci
# IP: The module: 'async_fifo_28by256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/kintex_map_5cam_Y8_4dec/kintex_5cam/kintex_camlink_tx_231023.gen/sources_1/ip/async_fifo_28by256/async_fifo_28by256.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_28by256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/kintex_map_5cam_Y8_4dec/kintex_5cam/kintex_camlink_tx_231023.gen/sources_1/ip/async_fifo_28by256/async_fifo_28by256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_28by256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/kintex_map_5cam_Y8_4dec/kintex_5cam/kintex_camlink_tx_231023.gen/sources_1/ip/async_fifo_28by256/async_fifo_28by256_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_28by256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
